# These are supported funding model platforms
# Uncomment and fill in the platforms you want to use

# github: [user1, user2] # Replace with up to 4 GitHub Sponsors-enabled usernames
# patreon: user # Replace with a single Patreon username
# open_collective: project # Replace with a single Open Collective username
# ko_fi: user # Replace with a single Ko-fi username
# tidelift: npm/package-name # Replace with a single Tidelift platform-name/package-name
# community_bridge: project-name # Replace with a single Community Bridge project-name
# liberapay: user # Replace with a single Liberapay username
# issuehunt: user # Replace with a single IssueHunt username
# polar: user # Replace with a single Polar username
# buy_me_a_coffee: user # Replace with a single Buy Me a Coffee username
# thanks_dev: user # Replace with a single thanks.dev username
# custom: ['https://example.com', 'https://example2.com'] # Replace with up to 4 custom sponsorship URLs
