# This file was generated by GoReleaser. DO NOT EDIT.
cask "riot" do
  name "riot"
  desc "RIoT - A Go application"
  homepage "https://github.com/fabianopinto/riot"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "riot"

  on_macos do
    on_intel do
      url "https://github.com/fabianopinto/riot/releases/download/v#{version}/riot_#{version}_Darwin_x86_64.tar.gz"
      sha256 "b1f1d42bc38dec22f5e480d7ce05316daad14b3919893bc4c150f4ff03d334e1"
    end
    on_arm do
      url "https://github.com/fabianopinto/riot/releases/download/v#{version}/riot_#{version}_Darwin_arm64.tar.gz"
      sha256 "30f39d53485ac95b4383116ccb69c9cf5f6463b92c690356b5ebbc6d2ede5601"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fabianopinto/riot/releases/download/v#{version}/riot_#{version}_Linux_x86_64.tar.gz"
      sha256 "00953d500fe64225e1424b48ba91a3b43f213bc8b9b26b2e781ab691ef3080c6"
    end
    on_arm do
      url "https://github.com/fabianopinto/riot/releases/download/v#{version}/riot_#{version}_Linux_arm64.tar.gz"
      sha256 "5780c71bd6c2f7a6c18fe43c598459d669e395ff51b707eaaf7d9fd7dbf3bc81"
    end
  end

  # No zap stanza required
end
